name: Build RansomWhere

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up latest Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Show available Xcode schemes
        run: xcodebuild -list -workspace RansomWhere.xcworkspace

      - name: Build Installer (unsigned)
        run: |
          xcodebuild \
            -workspace RansomWhere.xcworkspace \
            -scheme Installer \
            -configuration Release \
            CODE_SIGN_IDENTITY= \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS= \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: RansomWhere_Installer
          path: |
            ~/Library/Developer/Xcode/DerivedData/RansomWhere-*/Build/Products/Release/RansomWhere_Installer.app

      # Если нужен Daemon, добавь аналогичный шаг:
      # - name: Build Daemon (unsigned)
      #   run: |
      #     xcodebuild \
      #       -workspace RansomWhere.xcworkspace \
      #       -scheme Daemon \
      #       -configuration Release \
      #       CODE_SIGN_IDENTITY= \
      #       CODE_SIGNING_REQUIRED=NO \
      #       CODE_SIGN_ENTITLEMENTS= \
      #       CODE_SIGNING_ALLOWED=NO \
      #       clean build
      # - name: Upload Daemon artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: RansomWhere_Daemon
      #     path: |
      #       ~/Library/Developer/Xcode/DerivedData/RansomWhere-*/Build/Products/Release/Daemon
