name: Build RansomWhere

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14 # или macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Print Xcode version (для дебага)
      run: xcodebuild -version

    - name: Build Daemon (skip signing)
      run: |
        xcodebuild -workspace RansomWhere.xcworkspace -scheme Daemon -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Build Installer (skip signing & ignore missing Daemon)
      run: |
        xcodebuild -workspace RansomWhere.xcworkspace -scheme Installer -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Upload Daemon binary
      uses: actions/upload-artifact@v4
      with:
        name: Daemon
        path: '**/Daemon'

    - name: Upload Installer binary
      uses: actions/upload-artifact@v4
      with:
        name: Installer
        path: '**/Installer'
