name: Build Daemon & Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Daemon (skip signing)
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace \
            -scheme Daemon \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Check Daemon binary exists
        run: |
          DAEMON_PATH=$(find ~/Library/Developer/Xcode/DerivedData/ -type f -name Daemon -print -quit)
          if [ -z "$DAEMON_PATH" ]; then
            echo "Daemon binary not found!"
            exit 1
          fi
          echo "Daemon found at $DAEMON_PATH"

      - name: Build Installer (skip signing)
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace \
            -scheme Installer \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Prepare and upload artifacts
        run: |
          mkdir -p artifacts
          DAEMON_PATH=$(find ~/Library/Developer/Xcode/DerivedData/ -type f -name Daemon -print -quit)
          INSTALLER_PATH=$(find ~/Library/Developer/Xcode/DerivedData/ -type f -name Installer -print -quit)
          cp "$DAEMON_PATH" artifacts/Daemon
          cp "$INSTALLER_PATH" artifacts/Installer
        # Эта команда может быть actions/upload-artifact@v4 для каждого бинаря:
      - name: Upload Daemon
        uses: actions/upload-artifact@v4
        with:
          name: Daemon
          path: artifacts/Daemon
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: artifacts/Installer
