name: Build RansomWhere

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build Daemon (unsigned)
        run: |
          xcodebuild \
            -workspace RansomWhere.xcworkspace \
            -scheme Daemon \
            -configuration Release \
            CODE_SIGN_IDENTITY= \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS= \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Build Installer (unsigned)
        run: |
          xcodebuild \
            -workspace RansomWhere.xcworkspace \
            -scheme Installer \
            -configuration Release \
            CODE_SIGN_IDENTITY= \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS= \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: RansomWhere_Installer
          path: |
            ~/Library/Developer/Xcode/DerivedData/RansomWhere-*/Build/Products/Release/RansomWhere_Installer.app
