name: Build RansomWhere

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build Daemon
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace -scheme Daemon -configuration Release build

      - name: Build Installer
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace -scheme Installer -configuration Release build

      - name: Upload Daemon binary
        uses: actions/upload-artifact@v4
        with:
          name: Daemon
          path: |
            ./Build/Products/Release/Daemon

      - name: Upload Installer binary
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: |
            ./Build/Products/Release/RansomWhere_Installer.app
