name: Build RansomWhere

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Daemon (skip signing)
        run: |
          xcodebuild \
            -workspace RansomWhere.xcworkspace \
            -scheme Daemon \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Find Daemon binary
        run: |
          find . -name Daemon -type f || true

      - name: Build Installer (skip signing)
        run: |
          xcodebuild \
            -workspace RansomWhere.xcworkspace \
            -scheme Installer \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Find Installer binary
        run: |
          find . -name Installer -type f || true

      - name: Upload all Daemon binaries
        uses: actions/upload-artifact@v4
        with:
          name: Daemon
          path: |
            **/Daemon

      - name: Upload all Installer binaries
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: |
            **/Installer
