name: Build Daemon

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Daemon (skip signing)
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace \
            -scheme Daemon \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Find built Daemon binary
        id: find_daemon
        run: |
          BIN_PATH=$(find ~/Library/Developer/Xcode/DerivedData/ -type f -name Daemon -print -quit)
          if [ -z "$BIN_PATH" ]; then
            echo "Daemon binary not found!"
            exit 1
          fi
          echo "Found Daemon at $BIN_PATH"
          echo "BIN_PATH=$BIN_PATH" >> $GITHUB_ENV

      - name: Copy Daemon binary to artifacts folder
        run: |
          mkdir -p artifacts
          cp "$BIN_PATH" artifacts/Daemon

      - name: Upload Daemon binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: Daemon
          path: artifacts/Daemon
