name: Build RansomWhere

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install latest Git
        run: brew install git || true

      - name: Install Carthage (если нужен)
        run: brew install carthage || true

      - name: List available Xcode schemes
        run: xcodebuild -list -workspace RansomWhere.xcworkspace

      - name: Build with Xcode (Installer, без подписи)
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace \
          -scheme Installer \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_ENTITLEMENTS="" \
          CODE_SIGNING_ALLOWED=NO \
          clean build
