name: Build RansomWhere

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build Daemon (skip signing)
        run: |
          xcodebuild \
            -workspace RansomWhere.xcworkspace \
            -scheme Daemon \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Build Installer (skip signing & ignore missing Daemon)
        run: |
          xcodebuild \
            -workspace RansomWhere.xcworkspace \
            -scheme Installer \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_ALLOWED=NO \
            build || true

      - name: Upload Daemon binary
        uses: actions/upload-artifact@v4
        with:
          name: Daemon
          path: |
            **/Daemon
            **/Daemon.app

      - name: Upload Installer binary
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: |
            **/RansomWhere_Installer.app
            **/Installer
            
