name: Build Installer (skip signing)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Daemon (skip signing)
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace \
            -scheme Daemon \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Find Daemon binary
        id: find_daemon
        run: |
          DAEMON_BIN=$(find ~/Library/Developer/Xcode/DerivedData/ -type f -name Daemon -print | grep -v dSYM | head -1)
          if [ -z "$DAEMON_BIN" ]; then
            echo "Daemon binary not found!"
            exit 1
          fi
          echo "Found Daemon at $DAEMON_BIN"
          mkdir -p Installer
          cp "$DAEMON_BIN" Installer/Daemon
          ls -lh Installer/Daemon
          file Installer/Daemon

      - name: Build Installer (skip signing)
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace \
            -scheme Installer \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Upload Daemon binary
        uses: actions/upload-artifact@v4
        with:
          name: Daemon
          path: Installer/Daemon
