    - name: Build Installer (skip signing)
      run: |
        # Сборка Daemon и Installer
        xcodebuild -workspace RansomWhere.xcworkspace \
          -scheme Daemon -configuration Release \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

        xcodebuild -workspace RansomWhere.xcworkspace \
          -scheme Installer -configuration Release \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

        # Найти бинарник Daemon (НЕ из dSYM)
        DAEMON_BIN=$(find ~/Library/Developer/Xcode/DerivedData/ -type f -name Daemon | grep -v dSYM | head -1)
        echo "Found Daemon binary at $DAEMON_BIN"

        # Копировать бинарь в Installer (если надо — в нужное место для сборки)
        # Например, если скрипт в build phase Installer, можно так:
        cp "$DAEMON_BIN" Installer/Daemon

        # Проверить что файл реально скопирован и исполняемый
        ls -lh Installer/Daemon
        file Installer/Daemon
