name: Build RansomWhere

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Daemon
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace -scheme Daemon -configuration Release \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO build

      - name: Build Installer
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace -scheme Installer -configuration Release \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO build

      - name: Upload Daemon binary
        uses: actions/upload-artifact@v4
        with:
          name: Daemon
          path: '**/Daemon'  # поменяй путь если бинарь в другом месте

      - name: Upload Installer binary
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: '**/Installer'  # поменяй путь если бинарь в другом месте
