name: Build RansomWhere

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Daemon
        run: xcodebuild -workspace RansomWhere.xcworkspace -scheme Daemon -configuration Release build

      - name: Build Installer
        run: xcodebuild -workspace RansomWhere.xcworkspace -scheme Installer -configuration Release build

      - name: Upload Daemon binary
        uses: actions/upload-artifact@v4
        with:
          name: Daemon
          path: '**/Daemon'  # путь до бинаря, поправь если надо

      - name: Upload Installer binary
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: '**/RansomWhere_Installer.app'  # путь до .app, поправь если надо
