name: Build RansomWhere

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: actions/setup-xcode@v4
      with:
        xcode-version: '15.4'

    - name: Build Daemon (skip signing)
      run: |
        xcodebuild -workspace RansomWhere.xcworkspace -scheme Daemon -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Build Installer (skip signing & ignore missing Daemon)
      run: |
        xcodebuild -workspace RansomWhere.xcworkspace -scheme Installer -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Upload Daemon binary
      uses: actions/upload-artifact@v4
      with:
        name: Daemon
        path: '**/Daemon'  # уточни путь если надо

    - name: Upload Installer binary
      uses: actions/upload-artifact@v4
      with:
        name: Installer
        path: '**/Installer'  # уточни путь если надо
