name: Build RansomWhere

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    # Сборка Daemon (skip signing)
    - name: Build Daemon (skip signing)
      run: |
        xcodebuild -workspace RansomWhere.xcworkspace -scheme Daemon -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    # Проверяем, где лежит бинарь
    - name: List Release products
      run: ls -lR ./Daemon || true

    - name: Find Daemon binary
      run: find . -name Daemon -type f || true

    # Сборка Installer (skip signing и игнор отсутствия Daemon)
    - name: Build Installer (skip signing)
      run: |
        xcodebuild -workspace RansomWhere.xcworkspace -scheme Installer -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: List Installer products
      run: ls -lR ./Installer || true

    - name: Find Installer binary
      run: find . -name Installer -type f || true

    # Загрузка бинарей (пути укажешь после первого успешного ls/find!)
    - name: Upload Daemon binary
      uses: actions/upload-artifact@v4
      with:
        name: Daemon
        path: '**/Daemon' # ОБНОВИ после первого успешного ls/find на конкретный путь!

    - name: Upload Installer binary
      uses: actions/upload-artifact@v4
      with:
        name: Installer
        path: '**/Installer' # ОБНОВИ после первого успешного ls/find на конкретный путь!
