name: Build Installer (skip signing)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Daemon binary exists
        run: |
          if [ ! -f Installer/Daemon ]; then
            echo "ERROR: Daemon binary not found in Installer/Daemon"
            exit 1
          fi
          chmod +x Installer/Daemon
          echo "Daemon binary is ready:"
          file Installer/Daemon
          ls -lh Installer/Daemon

      - name: Build Installer (skip signing)
        run: |
          xcodebuild -workspace RansomWhere.xcworkspace \
            -scheme Installer \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: Installer/build/Release/
